sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:

    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tGjTVZx1RYJXqvXVjLk
    access-key-secret: DRtUXCaq2ksXlMfvpw7aWGyEm9YJAg
    bucket-name: ty-sky-take-out-study